sudo: false
language: node_js
node_js:
  - 10
branches:
  only:
    - master
before_script:
  - npm prune
script:
  - npm run test
  - npm run coverage-check
after_success:
  - npm run coverage-report
  - npm run semantic-release
