sudo: false
language: node_js
node_js:
  - "10.13.0"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
